library(darch)
library(data.table)
specify_decimal <- function(x, k) format(round(x, k), nsmall=k)
args = commandArgs(trailingOnly=TRUE)
darch=loadDArch(paste(getwd(),"/script/autosave_10",sep=""))
print(args)
f1=fread(args[1],sep=",")
f2=read.table(args[2])
predictions <- specify_decimal(predict(darch,f1),3)
f2=cbind(f2,predictions)
write.table(file=paste(args[1],"_pred",sep=""),f2,row.names=FALSE,col.names=FALSE,quote=FALSE)
